name: coffee_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.6.0
  awesome_extensions: ^2.0.9
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  go_router: ^11.1.4
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  equatable: ^2.0.5
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  firebase_analytics: ^10.5.1
  firebase_remote_config: ^4.2.7
  image_picker: ^1.0.4
  firebase_auth: ^4.10.1
  firebase_storage: ^11.2.8
  cloud_firestore: ^4.9.3
  mask_text_input_formatter: ^2.5.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  uuid: ^4.1.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter/Inter-Light.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter/Inter-Thin.ttf
    - family: Besley
      fonts:
        - asset: assets/fonts/besley/Besley-Black.ttf
        - asset: assets/fonts/besley/Besley-Bold.ttf
        - asset: assets/fonts/besley/Besley-ExtraBold.ttf
        - asset: assets/fonts/besley/Besley-Medium.ttf
        - asset: assets/fonts/besley/Besley-Regular.ttf
